### ISSUE TITLE
some problem with bokeh serve

### ISSUE THREAD

**Issue by dujiahei** [fdebrain/Brain-Computer-Interface-Cybathlon2020#21]
Dear Frederic，

Hi，I meet some problem when run "bokeh serve bokeh_dashboard --show".  

ERROR: Path for Bokeh server application does not exist: D:\Users\lenovo\Downloads\Brain-Computer-Interface-Cybathlon2020-master\Brain-Computer-Interface-Cybathlon2020-master\code\bokeh_dashboard
![image](https://user-images.githubusercontent.com/32332823/135240894-324cc8d0-bea8-46e9-a8cf-94d3b09363ef.png)

I have no idea why and how to solve it.

Thank you!

**Comment by fdebrain** [comment]
Hi dujiahei, sorry for the late answer. I updated the readme, the correct command should be "bokeh serve main --show"
